# Generated by Django 2.1.5 on 2019-02-04 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 2, 4, 19, 49, 15, 587267))),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
            ],
        ),
    ]
