# Generated by Django 2.1.5 on 2019-02-04 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 20, 19, 15, 114168)),
        ),
    ]
