# Generated by Django 2.1.5 on 2019-02-18 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190218_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 20, 12, 59, 152626)),
        ),
    ]
