# Generated by Django 2.1.5 on 2019-04-01 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190218_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summury', models.CharField(max_length=200)),
                ('url_slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='blog_news',
            name='url_slug_news',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 20, 15, 52, 315245)),
        ),
        migrations.AddField(
            model_name='blog_news',
            name='news_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Categories'),
        ),
    ]
