# Generated by Django 2.1.5 on 2019-04-08 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190401_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 20, 10, 12, 818380)),
        ),
    ]
