# Generated by Django 2.1.5 on 2019-04-15 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190408_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 19, 45, 44, 936935)),
        ),
    ]
